version: "3"
services:
  react:
    container_name: "react"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: "/root"
    volumes:
      - "./:/root"
    command: sh -c "npm i && npm run build && npm run start"
    ports:
      - "3000:3000"